from typing import List

from abstract_scraper import Scraper
from model import Book, Chapter


class BlinkistScraperMock(Scraper):

    def scrape(self) -> List[Book]:
        chapter1 = Chapter(id='54b3a6e06466330009120000',
                           order_number=1,
                           title='Was drin ist für dich: Die einzige Regel kennenlernen, die du brauchst, um an der Börse Geld zu verdienen.',
                           text='<p>Wer wünscht sich das nicht: Mit relativ wenig Aufwand ein anständiges Einkommen erzielen. Vielleicht hast du auch schon einmal darüber nachgedacht, es an der Börse zu versuchen? Aber irgendwie scheint das auch alles viel zu kompliziert zu sein. Wie soll jemand, der eigentlich etwas ganz Anderes gelernt hat, zwischen den ganzen ausgebildeten Finanzhaien überhaupt eine Chance haben? Müssen wir dazu nicht furchtbar komplizierte Formeln kennen und den ganzen Tag die Börsenkurse auf dem Schirm haben?</p>\n<p>Nein! Es ist überhaupt nicht schwer, mit Aktien ein kleines oder großes Vermögen zu verdienen. Phil Town hatte z.B., bis er über 30 Jahre alt war, überhaupt nichts mit der Finanzwelt zu tun. Er war Elitesoldat bei der US-Army und arbeitete danach für ein Unternehmen, das Rafting-Touren anbot. Doch eines Tages ging eine Tour ziemlich schief und er bewahrte einen erfolgreichen Investor vor einem Unfall. Aus Dankbarkeit weihte dieser ihn in die Geheimnisse seines Erfolgs ein.</p>\n<p>Phil Town startete mit $1000 und hatte fünf Jahre später seine erste Million auf dem Konto. Alles, was er tat, war, sich an ein paar ganz simple Regeln zu halten, die ihm der Investor erklärt hatte. In <em>Regel Nummer 1</em> gibt er diese Tipps weiter. Du musst wirklich kein Finanzexperte sein, um die einfachen Regeln zu verstehen, mit denen jeder an der Börse erfolgreich sein kann. Lies die folgenden Blinks und du hast alles, was du brauchst.</p>\n<p>In diesen Blinks wirst du außerdem herausfinden,</p>\n<ul>\n<li>welche Statistiken beweisen, dass eine Firma richtig gut ist,</li>\n<li>warum der Markt nicht so effizient ist, wie du vielleicht glaubst, und</li>\n<li>warum ein diversifiziertes Portfolio auch kein Wundermittel ist.</li>\n</ul>'
                           )

        chapter2 = Chapter(id='54b3a6ff6466330009140000',
                           order_number=2,
                           title='Quereinsteiger: Wir müssen keine Experten sein, um geschickt zu investieren.',
                           text='<p>Die meisten Menschen glauben, dass sie ohne die Hilfe eines Finanzberaters an der Börse auf jeden Fall ihr ganzes Geld verlieren würden. Finanzexperten haben das schließlich studiert und jahrelange Erfahrung auf dem Börsenparkett gesammelt. Wie könnte es also sein, dass ein absoluter Anfänger da mithalten kann?</p>\n<p>Das geht tatsächlich! Wir müssen gar nicht alle Regeln und Tricks der Finanzwelt kennen, es reicht, wenn wir die wichtigsten beherrschen – und die lernen wir in den nächsten Blinks kennen. Außerdem stellt uns das Internet heute Informationen zur Verfügung, die lange Zeit den Experten vorbehalten waren. Die Kurshistorie von Aktien und Statistik-Rechner erledigen online schon einen großen Teil der Arbeit. Auf Websites wie MSN Money, Yahoo Finance oder CNN Money finden wir Daten zu Tausenden Aktien, und ruleoneinvesting.com bietet alle wichtigen Rechner an, sodass wir uns keine einzige Formel merken müssen.</p>\n<p>Mit diesen Tricks und Informationen ausgestattet gelingt es uns nicht nur, besser als die Finanzexperten zu investieren, sondern sogar schlauer zu werden als der Markt selbst. Das klingt zuerst einmal merkwürdig, denn laut der <em>Effizienzmarkttheorie</em> ist so etwas nicht möglich: Sie besagt, dass der Markt automatisch immer den genauen Wert einer Firma durch ihren Preis ermittelt. Alle Informationen, die über eine Firma bekannt sind, schlagen sich sofort im Preis ihrer Aktie nieder.</p>\n<p>Aber die Effizienzmarkttheorie ist falsch. Der Preis einer Aktie entspricht nicht immer ihrem tatsächlichen Wert. Das sehen wir z.B. daran, dass immer wieder Blasen aus überbewerteten Aktien entstehen oder Leute wie Warren Buffett es schaffen, für 20 Jahre am Stück mit ihren Investments über 15% Gewinn zu machen.</p>\n<p>Sehen wir uns also an, was wir wissen müssen, um schlauer zu sein als die meisten, und mit wenig Risiko gutes Geld an der Börse zu verdienen.</p>'
                           )

        chapter3 = Chapter(id='54b3a7136466330009160000',
                           order_number=3,
                           title='Vollkommen überbewertet: Ein diversifiziertes Portfolio ist nicht immer eine gute Idee.',
                           text='<p>Wer sich schon einmal mit Investments und Aktien beschäftigt hat, hat sicher schon einmal davon gehört, dass er unbedingt auf ein diversifiziertes Portfolio achten sollte. Es klingt ja auch einleuchtend: Wer Aktien von möglichst vielen Firmen in unterschiedlichen Bereichen hat, minimiert sein Risiko. Denn wenn eine Aktie abstürzt oder eine Industrie in eine Krise schlittert, haben wir ja noch die anderen, in denen unser Geld sicher angelegt ist.</p>\n<p>Aber die Erfahrung spricht eine andere Sprache: Wenn wir uns ansehen, wie sich langfristige diversifizierte Portfolios in den letzten 100 Jahren entwickelt haben, dann müssen wir feststellen, dass wir damit in 60 von 100 Jahren überhaupt keinen Gewinn gemacht hätten. Denn in so einem Portfolio steigen zwar immer einige Aktien im Preis, aber dafür fallen viele andere, sodass wir am Ende auch nicht mehr Geld haben.</p>\n<p>Außerdem ist es wichtig für die Sicherheit unserer Anlagen, dass wir unsere Aktien immer aufmerksam beobachten – und das wird schwieriger, je mehr unterschiedliche Aktien wir besitzen. Im Idealfall sind wir über die Firmen, deren Aktien wir besitzen, über ihre Finanzen und ihre Entwicklung gut informiert. Doch wenn wir viele Aktien besitzen, haben wir gar nicht genug Zeit, um all diese Informationen zu verarbeiten. Dann sind wir den Preisschwankungen unvorbereitet ausgesetzt.</p>\n<p>Außerdem müssen wir an der Börse manchmal schnell reagieren, und das ist natürlich leichter, wenn wir nur ein paar wenige Aktien im Blick behalten müssen. Am geschicktesten ist es natürlich, wenn wir in Bereichen investieren, in denen wir uns gut auskennen. Apotheker sollten z.B. in Pharmaunternehmen investieren – denn sie bekommen regelmäßige Updates darüber, bei welchen Medikamenten neue Nebenwirkungen entdeckt wurden, und haben damit einen Informationsvorsprung vor anderen Anlegern im Pharmabereich.</p>\n<p>Es ist natürlich dumm, sein ganzes Vermögen in eine einzige Aktie zu stecken. Aber genauso dumm ist es, einfach alle möglichen Aktien durcheinander zu kaufen, nur um sein Portfolio zu diversifizieren. Stattdessen sollten wir einige wenige, aber hervorragende Aktien auswählen. Wie wir sie finden, erfahren wir in den nächsten Blinks.</p>')

        book = Book(id='SomeRandomId',
                    published_at='2015-01-13T00:00:00.000+00:00',
                    title='Regel Nummer 1',
                    subtitle='Einfach erfolgreich anlegen!',
                    author='Phil Town',
                    language='de',
                    about_the_book='<p>Wie lässt sich an der Börse mit wenig Risiko Geld verdienen? <em>Regel Nummer 1</em> ist ein Ratgeber, der Börsenneulingen alles erklärt, was sie brauchen, um die vielversprechendsten Aktien zu finden, zum richtigen Zeitpunkt zu kaufen und später mit Gewinn wieder zu verkaufen. Dazu ist es nicht nötig, Wirtschaft oder Finanzen studiert zu haben; es reicht, sich an ein paar einfache und leicht verständliche Richtlinien zu halten.</p>',
                    teaser='Einfach erfolgreich anlegen!',
                    who_should_read='<ul>\n<li>Jeder, der mit relativ wenig Aufwand ein sicheres Einkommen erzielen möchte</li>\n<li>Jeder, der schon immer wissen wollte, wie der Aktienhandel funktioniert</li>\n<li>Jeder Investor und alle, die es werden wollen</li>\n</ul>',
                    about_the_author='<p>Phil Town diente nach der Universität in einer Elite-Einheit der US-Army. Danach arbeitete er als Guide für Rafting-Touren. Nachdem er einem Investor auf einer dieser Touren das Leben gerettet hatte, erklärte dieser Phil Town die Geheimnisse des erfolgreichen Investierens. Seitdem hat er innerhalb von 5 Jahren an der Börse seine erste Million gemacht und ist heute ein erfolgreicher Investor, Autor und Motivations-Redner.</p>',
                    market='mainstream',
                    image_url='https://images.blinkist.com/images/books/54b3a6b76466330009110000/3_4/640.jpg',
                    chapters=[chapter1, chapter2, chapter3]
                    )
        return [book]
